// =====================================================================
// Site data — Plomberie Services 91 / chauffagiste-industriel.fr
// Source : arborescence Avril 2026 + service-data du wireframe
// =====================================================================

const SITE = {
  brand: "Plomberie Services 91",
  domain: "chauffagiste-industriel.fr",
  phone: "06 33 82 30 23",
  phoneAlt: "06 31 79 35 05",
  email: "contact@plomberieservices91.com",
  address: "26 Grande Rue, 45170 Oison",
  socials: { linkedin: "@plomberie-services-91", instagram: "@plomberieservices91" },
};

const CERTS = ["QualiGaz", "RGE", "QualiPAC", "QualiBois", "Station SEET", "Garantie décennale"];

// ---------- Top-level navigation ----------
const NAV = [
  {
    label: "Chauffage industriel",
    href: "/chauffagiste-industriel/",
    submenu: [
      ["Chauffage gaz industriel", "/chauffage-industriel/chauffage-gaz/"],
      ["Chauffage hangar industriel", "/chauffage-industriel/chauffage-hangar/"],
      ["Chaufferie industrielle", "/chauffage-industriel/chaufferie-industrielle/"],
      ["Aérotherme industriel", "/chauffage-industriel/aerotherme/"],
      ["Chauffage radiant", "/chauffage-industriel/chauffage-radiant/"],
      ["Maintenance chaufferie", "/chauffage-industriel/maintenance-chaufferie/"],
      ["Chauffage collectif", "/chauffage-industriel/chauffage-collectif/"],
      ["Chauffage électrique collectif", "/chauffage-industriel/chauffage-electrique-collectif/"],
      ["— Essonne (91)", "/chauffage-industriel-essonne/"],
      ["— Loiret (45)", "/chauffage-industriel-loiret/"],
    ],
    key: "indus",
  },
  {
    label: "Chauffagiste",
    href: "/chauffagiste/",
    submenu: [
      ["Hub Chauffagiste", "/chauffagiste/"],
      ["Chauffagiste Essonne", "/chauffagiste-essonne/"],
      ["Chauffagiste Loiret", "/chauffagiste-loiret/"],
    ],
    key: "chauffagiste",
  },
  {
    label: "Devis",
    href: "/devis-chauffage-industriel/",
    submenu: [
      ["Devis chauffage industriel", "/devis-chauffage-industriel/"],
      ["Devis chauffagiste", "/devis-chauffagiste/"],
      ["Devis installation chauffage", "/devis-installation-chauffage/"],
      ["Devis dépannage chauffage", "/devis-depannage-chauffage/"],
      ["Devis maintenance chauffage", "/devis-maintenance-chauffage/"],
      ["Devis plombier chauffagiste", "/devis-plombier-chauffagiste/"],
      ["Devis chauffagiste Essonne", "/devis-chauffagiste-essonne/"],
      ["Devis chauffagiste Loiret", "/devis-chauffagiste-loiret/"],
      ["Devis chauffagiste IDF", "/devis-chauffagiste-ile-de-france/"],
    ],
    key: "devis",
  },
  { label: "Blog", href: "/blog/", key: "blog" },
  { label: "Contact", href: "/contact/", key: "contact" },
];

// ---------- 8 fiches du silo /chauffage-industriel/ ----------
const HUB_INDUSTRIEL_SLUG = "chauffagiste-industriel";
const HUB_INDUSTRIEL_PATH = "/chauffagiste-industriel/";

const SERVICES_INDUSTRIEL = [
  {
    slug: "chauffage-gaz",
    path: "/chauffage-industriel/chauffage-gaz/",
    nav: "Chauffage gaz industriel",
    breadcrumb: "Chauffage gaz industriel",
    h1: "Chauffage gaz industriel — installation et mise en conformité.",
    title: "Chauffage Gaz Industriel — Solutions Performantes | Plomberie Services 91",
    metaDesc: "Installation et mise aux normes ICPE de chauffage gaz industriel en Essonne, Loiret et Île-de-France. Chaudières, aérothermes gaz, contrats P1/P2/P3.",
    keyword: "chauffage gaz industriel",
    icon: "flame",
    lead: "Solutions gaz pour usines, entrepôts et chaufferies tertiaires. Conception, raccordement, mise en conformité ATEX et contrats de maintenance P1/P2/P3.",
    heroPhoto: "PHOTO CHAUFFERIE GAZ INDUSTRIELLE",
    intro_h2: "Le chauffage gaz industriel, performance et conformité.",
    def_h2: "Qu'appelle-t-on chauffage gaz industriel ?",
    def_body: "Toute installation gaz au-delà de 70 kW classée ICPE rubrique 2910. Concerne aussi bien les chaudières gaz, les aérothermes gaz, les radiants gaz que les générateurs d'air chaud direct.",
    def_features: [
      "Puissances de 70 kW à plusieurs MW",
      "Gaz naturel, propane, biogaz",
      "Conformité ATEX et ICPE 2910",
      "Compatible décret tertiaire 2027",
    ],
    schema_label: "SCHÉMA RÉSEAU GAZ\n(arrivée · détente · chaudière · sécurités)",
    benefits_h2: "Les avantages d'une installation gaz industrielle.",
    benefits: [
      ["chart", "Coût d'exploitation maîtrisé", "Énergie compétitive sur les volumes industriels."],
      ["bolt", "Puissance disponible", "De 70 kW à plusieurs MW selon vos besoins."],
      ["shield", "Conformité ICPE", "Mise aux normes réglementaires rubrique 2910."],
      ["wrench", "Maintenance contractualisée", "Contrats P1/P2/P3 sur-mesure."],
      ["flame", "Biogaz et hybride", "Solutions de transition décarbonée."],
      ["award", "CEE et aides ADEME", "Optimisation des financements."],
    ],
    buildings: ["Usines de production", "Entrepôts logistiques", "Hangars agricoles", "Bâtiments tertiaires", "Établissements scolaires", "Hôpitaux", "Casernes", "Centres commerciaux", "Sites industriels classés"],
    process_h2: "Notre processus pour une installation gaz industrielle.",
    process: ["Audit énergétique et étude ICPE", "Conception et dimensionnement", "Installation et raccordement", "Mise en service et maintenance"],
    brands: ["Frisquet", "Atlantic", "De Dietrich", "Viessmann", "Bosch", "Riello"],
    case_h3: "Refonte chaufferie gaz — site logistique 12 000 m².",
    case_body: "Remplacement de 4 chaudières fioul vétustes par 2 chaudières gaz à condensation cascade 1 200 kW + mise aux normes ICPE.",
    case_metrics: [["Puissance installée", "1 200 kW"], ["Émissions CO₂", "−42%"], ["Économies / an", "31 500 €"], ["Conformité ICPE", "✓ Validée"]],
    pricing_h2: "Comment se construit votre devis chauffage gaz.",
    pricing_factors: [
      ["Puissance et profil", "Régime continu ou intermittent, pointes de besoin."],
      ["Raccordement réseau", "Distance au réseau gaz, détente nécessaire."],
      ["Mise en conformité", "Audit ICPE, ATEX, sécurités gaz."],
      ["Maintenance P1/P2/P3", "Niveau d'engagement contractuel."],
    ],
    faq_h2: "Questions sur le chauffage gaz industriel.",
    faqs: [
      ["Mon site est-il classé ICPE 2910 ?", "Toute installation gaz dont la puissance cumulée dépasse 1 MW est soumise à déclaration ou enregistrement ICPE rubrique 2910. Nous réalisons l'audit ICPE complet."],
      ["Gaz naturel ou propane : quelle solution ?", "Le gaz naturel (réseau GRDF) est privilégié quand le site est raccordé. Le propane (cuve) reste pertinent en zone non desservie ou pour des usages intermittents."],
      ["Quelle différence entre P1, P2 et P3 ?", "P1 = fourniture combustible, P2 = conduite et entretien courant, P3 = garantie totale matériel. Le plus courant est un P2+P3 chez l'industriel."],
      ["Quel délai pour une mise en conformité ?", "De 4 à 12 semaines selon l'ampleur des écarts constatés et la disponibilité des pièces de sécurité. Nous priorisons les non-conformités majeures."],
      ["Le biogaz est-il une option ?", "Oui, en injection sur le réseau GRDF (BioGNV) ou via une production sur site. Pertinent pour décarboner sans changer le matériel."],
    ],
    cta_h2: "Projet de chauffage gaz industriel ? Parlons-en.",
  },
  {
    slug: "chauffage-hangar",
    path: "/chauffage-industriel/chauffage-hangar/",
    nav: "Chauffage hangar industriel",
    breadcrumb: "Chauffage hangar industriel",
    h1: "Chauffage hangar industriel — solutions sur-mesure.",
    title: "Chauffage Hangar Industriel — Aérothermes, Radiants, Solutions",
    metaDesc: "Solutions de chauffage pour hangars industriels en Essonne et Loiret : aérothermes, tubes radiants, panneaux infrarouges. Étude et installation sur-mesure.",
    keyword: "chauffage hangar industriel",
    icon: "factory",
    lead: "Aérothermes, radiants gaz, panneaux rayonnants. Nous dimensionnons la solution la plus efficace selon la hauteur, l'isolation et l'usage de votre hangar.",
    heroPhoto: "PHOTO HANGAR AVEC AÉROTHERMES SUSPENDUS",
    intro_h2: "Chauffer un hangar : les bonnes solutions.",
    def_h2: "Comment chauffer un hangar industriel ?",
    def_body: "Trois familles de solutions selon l'usage : aérothermes pour les grands volumes occupés, radiants gaz pour les zones de poste fixe, panneaux rayonnants pour les ateliers de production.",
    def_features: [
      "Aérothermes gaz ou eau chaude",
      "Tubes radiants gaz infrarouge",
      "Panneaux rayonnants haute température",
      "Solutions hybrides selon zones",
    ],
    schema_label: "SCHÉMA HANGAR\n(zoning · sources de chaleur · stratification)",
    benefits_h2: "Les avantages d'un chauffage hangar bien pensé.",
    benefits: [
      ["thermo", "Confort de poste", "Chaleur dirigée là où travaillent les opérateurs."],
      ["chart", "Économies par zoning", "Chauffer les zones occupées seulement."],
      ["clock", "Montée en température rapide", "Idéal pour les sites à occupation intermittente."],
      ["factory", "Toutes hauteurs", "De 4 à 20m sous plafond."],
      ["shield", "Sécurité incendie", "Solutions adaptées aux ERP et ICPE."],
      ["award", "Éligible CEE", "Primes pour le remplacement de chauffage électrique."],
    ],
    buildings: ["Hangars logistiques", "Hangars agricoles", "Ateliers mécaniques", "Garages et concessions", "Hangars de stockage", "Bâtiments d'élevage", "Hangars BTP", "Showrooms", "Salles de sport"],
    process_h2: "Notre processus pour le chauffage de votre hangar.",
    process: ["Visite et étude thermique sur site", "Choix de la techno (aérotherme / radiant)", "Installation et mise en service", "Suivi et maintenance"],
    brands: ["Reznor", "Sonniger", "Schwank", "Adrian", "Mark", "Robur"],
    case_h3: "Chauffage radiants gaz — concession auto Brétigny.",
    case_body: "Installation de 12 tubes radiants Schwank dans un atelier mécanique de 1 800 m² pour remplacer un chauffage électrique défaillant.",
    case_metrics: [["Surface chauffée", "1 800 m²"], ["Hauteur sous plafond", "8 m"], ["Économies / an", "−54%"], ["Confort poste", "+11°C ressenti"]],
    pricing_h2: "Comment se construit votre devis hangar.",
    pricing_factors: [
      ["Volume à chauffer", "Surface × hauteur × cible température."],
      ["Isolation", "Toiture, parois, étanchéité aux portes."],
      ["Zonage", "Postes fixes vs circulation vs stockage."],
      ["Énergie disponible", "Gaz, électricité, eau chaude existante."],
    ],
    faq_h2: "Questions sur le chauffage de hangars.",
    faqs: [
      ["Aérotherme ou radiant pour mon hangar ?", "L'aérotherme convient aux hangars bien isolés et occupés en continu. Le radiant est préférable en grande hauteur, en occupation intermittente ou en local mal isolé."],
      ["Comment chauffer un hangar mal isolé ?", "Le radiant infrarouge chauffe les corps et les surfaces sans dépendre de l'air ambiant — idéal en hangar mal isolé. On limite ainsi les pertes."],
      ["Quelle puissance pour 1 000 m² à 6m de hauteur ?", "Comptez environ 100 à 150 W/m³, soit 600 à 900 kW pour ce volume — à affiner selon isolation et cible de température."],
      ["Peut-on chauffer une zone ouverte ?", "Oui, uniquement avec des solutions radiantes haute température, dimensionnées pour la zone d'usage et non l'ensemble du volume."],
      ["Est-ce éligible aux CEE ?", "Oui pour le remplacement d'anciens chauffages électriques ou à combustion peu efficaces. Nous montons les dossiers CEE."],
    ],
    cta_h2: "Un hangar à chauffer ? Étudions ensemble.",
  },
  {
    slug: "chaufferie-industrielle",
    path: "/chauffage-industriel/chaufferie-industrielle/",
    nav: "Chaufferie industrielle",
    breadcrumb: "Chaufferie industrielle",
    h1: "Chaufferie industrielle — conception et mise aux normes.",
    title: "Chaufferie Industrielle — Conception, Installation et Normes",
    metaDesc: "Conception, rénovation et mise aux normes ICPE de chaufferies industrielles en Essonne, Loiret et IDF. Études, installation, contrats P1/P2/P3.",
    keyword: "chaufferie industrielle",
    icon: "factory",
    lead: "Conception, rénovation et mise aux normes ICPE de chaufferies industrielles. Études thermiques, dimensionnement, sécurités, contrats P1/P2/P3.",
    heroPhoto: "PHOTO SALLE CHAUFFERIE INDUSTRIELLE",
    intro_h2: "La chaufferie, cœur thermique de votre site.",
    def_h2: "Qu'est-ce qu'une chaufferie industrielle ?",
    def_body: "Local technique regroupant chaudières, circulateurs, ballons et accessoires de production de chaleur, classé ICPE 2910 dès 70 kW. Cas particuliers : ICPE 2921 pour les tours aéroréfrigérantes.",
    def_features: [
      "Chaudières gaz, fioul, biomasse, hybrides",
      "Conformité ICPE 2910 et 2921",
      "Sécurités gaz, ventilation, désenfumage",
      "Régulation et GTB intégrées",
    ],
    schema_label: "SCHÉMA CHAUFFERIE\n(production · distribution · sécurités · GTB)",
    benefits_h2: "Pourquoi soigner sa chaufferie ?",
    benefits: [
      ["shield", "Conformité ICPE", "2910, 2921, ATEX selon votre installation."],
      ["chart", "Économies durables", "−20 à −50% selon état initial."],
      ["bolt", "Disponibilité", "Cascade et redondance pour ne jamais tomber."],
      ["wrench", "Maintenance simplifiée", "Accès, repérage, organes en place."],
      ["flame", "Décarbonation", "Biomasse, biogaz, PAC haute température."],
      ["award", "Aides ADEME et CEE", "Financements à hauteur de 30 à 60%."],
    ],
    buildings: ["Industries lourdes", "Sites tertiaires", "Hôpitaux et cliniques", "Établissements scolaires", "Logements collectifs", "Mairies et collectivités", "Casernes", "Centres commerciaux", "ERP de toute taille"],
    process_h2: "Notre processus chaufferie industrielle.",
    process: ["Audit existant et étude ICPE", "Conception et plans d'exécution", "Travaux et mise en service", "Contrat de maintenance P1/P2/P3"],
    brands: ["Viessmann", "De Dietrich", "Atlantic Guillot", "Bosch Industrial", "Hoval", "Riello"],
    case_h3: "Rénovation chaufferie hôpital — Étampes.",
    case_body: "Remplacement de 3 chaudières fioul 600 kW par cascade gaz à condensation Hoval 1 800 kW + GTB centralisée et mise en conformité ICPE.",
    case_metrics: [["Puissance", "1 800 kW"], ["Émissions CO₂", "−47%"], ["Économies / an", "62 000 €"], ["Aides ADEME", "180 000 €"]],
    pricing_h2: "Comment se construit votre devis chaufferie.",
    pricing_factors: [
      ["Audit existant", "État chaudières, sécurités, conformité."],
      ["Puissance et redondance", "Continuité de service requise."],
      ["Énergie cible", "Gaz, biomasse, hybride."],
      ["GTB et supervision", "Niveau de pilotage souhaité."],
    ],
    faq_h2: "Questions sur les chaufferies industrielles.",
    faqs: [
      ["Ma chaufferie est-elle classée ICPE ?", "Oui dès 70 kW (déclaration) et 1 MW (enregistrement) en gaz/fioul. Nous identifions les rubriques applicables et les démarches associées."],
      ["Quel délai pour une rénovation complète ?", "Compter 3 à 6 mois entre l'audit et la mise en service pour une chaufferie collective de taille moyenne — étude, commandes, travaux, recette."],
      ["Biomasse ou gaz : que choisir ?", "La biomasse est imbattable pour la décarbonation mais demande place et logistique. Le gaz reste pertinent en cascade condensation, surtout en mixte avec une PAC."],
      ["Comment fonctionne un contrat P1/P2/P3 ?", "P1 = combustible, P2 = entretien et conduite, P3 = garantie totale matériel. Vous choisissez votre niveau d'engagement."],
      ["Quelles aides pour rénover ma chaufferie ?", "Fonds chaleur ADEME, CEE bonifiés, MaPrimeRénov' Copro, FEDER selon le profil. Cumuls fréquents jusqu'à 60% du montant des travaux."],
    ],
    cta_h2: "Un projet de chaufferie ? Parlons-en.",
  },
  {
    slug: "aerotherme",
    path: "/chauffage-industriel/aerotherme/",
    nav: "Aérotherme industriel",
    breadcrumb: "Aérotherme industriel",
    h1: "Aérotherme industriel — installation et maintenance.",
    title: "Aérotherme Industriel — Installation et Maintenance",
    metaDesc: "Installation, maintenance et remplacement d'aérothermes industriels en Essonne et Loiret. Modèles à condensation éligibles CEE. Devis sous 24h.",
    keyword: "aérotherme industriel",
    icon: "thermo",
    lead: "Chauffage soufflant pour grands volumes isolés. Installation, maintenance et remplacement par des modèles à condensation éligibles aux CEE.",
    heroPhoto: "PHOTO AÉROTHERME EN PLACE",
    intro_h2: "L'aérotherme, le chauffage soufflant des grands volumes.",
    def_h2: "Qu'est-ce qu'un aérotherme ?",
    def_body: "Un aérotherme combine un échangeur thermique (gaz, eau chaude ou électricité) et un ventilateur axial pour souffler de l'air chaud directement dans le volume à chauffer.",
    def_features: [
      "Échangeur thermique haute performance",
      "Ventilateur axial à débit ajustable",
      "Régulation thermostatique fine",
      "Modèles à condensation éligibles CEE",
    ],
    schema_label: "SCHÉMA TECHNIQUE ANNOTÉ\n(échangeur · ventilateur · sortie air chaud)",
    benefits_h2: "Les avantages pour votre site industriel.",
    benefits: [
      ["chart", "Économies énergétiques", "Jusqu'à 40% sur la consommation avec un modèle à condensation."],
      ["factory", "Adapté aux grands volumes", "Hangars, ateliers, entrepôts de 500 à 10 000 m²."],
      ["wrench", "Faible maintenance", "Une visite annuelle suffit pour un appareil bien dimensionné."],
      ["clock", "Longévité", "15 à 20 ans en exploitation industrielle."],
      ["shield", "Mise en conformité", "Compatible avec les exigences du décret tertiaire 2027."],
      ["award", "CEE éligibles", "Primes énergie pour le remplacement d'anciens appareils."],
    ],
    buildings: ["Entrepôts logistiques", "Hangars agricoles", "Ateliers de production", "Usines", "Locaux commerciaux", "Bâtiments tertiaires", "Centres de tri", "Plateformes industrielles", "Gymnases"],
    process_h2: "Notre processus pour l'installation d'aérothermes.",
    process: ["Étude thermique du bâtiment", "Dimensionnement et choix du combustible", "Installation et mise en service", "Contrat de maintenance"],
    brands: ["Frisquet", "Atlantic", "Daikin", "Mitsubishi", "Reznor", "Sonniger"],
    case_h3: "Installation de 8 aérothermes — Cristaline Les Ulis.",
    case_body: "Remplacement d'une installation vieillissante par 8 aérothermes à condensation Reznor pour un entrepôt logistique de 5 800 m².",
    case_metrics: [["Surface", "5 800 m²"], ["Puissance", "480 kW"], ["Économies réalisées", "−38% / an"], ["CEE perçus", "12 400 €"]],
    pricing_h2: "Comment se construit votre devis aérotherme.",
    pricing_factors: [
      ["Surface et hauteur", "Plus le volume est grand, plus la puissance requise augmente."],
      ["Combustible", "Gaz, eau chaude, électricité — coûts d'exploitation variables."],
      ["Isolation existante", "Détermine les pertes thermiques à compenser."],
      ["Régulation & GTB", "Pilotage à distance, optimisation horaire, suivi consos."],
    ],
    faq_h2: "Questions sur les aérothermes.",
    faqs: [
      ["Quelle puissance d'aérotherme pour mon hangar ?", "Comptez 50 à 100 W/m³ selon isolation et cible de température. Une étude thermique précise le dimensionnement et le nombre d'unités."],
      ["Aérotherme gaz ou eau chaude : que choisir ?", "Le gaz est autonome et puissant — idéal en hangar isolé. L'eau chaude est intéressante quand vous avez déjà une chaufferie et un réseau hydraulique."],
      ["Quelle est la durée de vie d'un aérotherme ?", "15 à 20 ans en exploitation industrielle, sous réserve d'une maintenance annuelle (échangeur, ventilateur, brûleur)."],
      ["Suis-je éligible aux CEE pour un remplacement ?", "Oui pour le remplacement d'aérothermes antérieurs à 2010 ou d'un chauffage électrique direct. Nous montons le dossier CEE."],
      ["À quelle fréquence faire la maintenance ?", "Une visite annuelle complète est recommandée — nettoyage, contrôle brûleur, sécurité gaz, vérification des débits d'air."],
    ],
    cta_h2: "Un projet d'aérotherme ? Parlons-en.",
  },
  {
    slug: "chauffage-radiant",
    path: "/chauffage-industriel/chauffage-radiant/",
    nav: "Chauffage radiant",
    breadcrumb: "Chauffage radiant",
    h1: "Chauffage radiant industriel — tubes et panneaux infrarouges.",
    title: "Chauffage Radiant Industriel — Infrarouge et Solutions",
    metaDesc: "Tubes radiants gaz et panneaux infrarouges pour ateliers, hangars et zones de poste. Installation et maintenance en Essonne et Loiret.",
    keyword: "chauffage radiant industriel",
    icon: "flame",
    lead: "Tubes radiants gaz et panneaux infrarouges pour chauffer les zones de travail directement, sans chauffer l'air. Idéal pour les hangars de grande hauteur et locaux ouverts.",
    heroPhoto: "PHOTO TUBES RADIANTS SUSPENDUS",
    intro_h2: "Le radiant : chauffer les hommes, pas l'air.",
    def_h2: "Comment fonctionne un chauffage radiant ?",
    def_body: "Le rayonnement infrarouge chauffe directement les corps et les surfaces dans son champ, sans passer par l'air. Résultat : confort immédiat même dans les volumes mal isolés ou ouverts.",
    def_features: [
      "Tubes radiants gaz suspendus",
      "Panneaux infrarouges haute température",
      "Démarrage et arrêt instantanés",
      "Zonage par poste de travail",
    ],
    schema_label: "SCHÉMA RAYONNEMENT IR\n(émetteur · cône de chauffe · zone confort)",
    benefits_h2: "Les avantages du chauffage radiant.",
    benefits: [
      ["thermo", "Confort immédiat", "Sensation de chaleur dès la mise en route."],
      ["chart", "Jusqu'à −60% conso", "Vs chauffage à air dans les grands volumes."],
      ["bolt", "Réactivité", "Démarrage et arrêt instantanés."],
      ["factory", "Idéal grandes hauteurs", "De 4 à 20m de hauteur sous plafond."],
      ["flame", "Pas de stratification", "Pas de perte par accumulation en plafond."],
      ["award", "Éligible CEE", "Pour remplacement d'anciens chauffages."],
    ],
    buildings: ["Hangars logistiques", "Ateliers mécaniques", "Garages auto", "Carrosseries", "Halls sportifs", "Terrasses extérieures", "Hangars d'élevage", "Concessions auto", "Locaux semi-ouverts"],
    process_h2: "Notre processus radiant infrarouge.",
    process: ["Étude des zones à chauffer", "Calcul du dimensionnement IR", "Installation et raccordement gaz", "Mise en service et maintenance"],
    brands: ["Schwank", "Adrian", "Sunradiant", "Carlieuklima", "Mark", "Sole"],
    case_h3: "Tubes radiants gaz — atelier industriel Pithiviers.",
    case_body: "Installation de 8 tubes radiants Schwank pour remplacer un chauffage électrique sous-dimensionné dans un atelier de 1 200 m² à 9 m de hauteur.",
    case_metrics: [["Surface", "1 200 m²"], ["Hauteur", "9 m"], ["Économies / an", "−61%"], ["Mise en chauffe", "< 8 min"]],
    pricing_h2: "Comment se construit votre devis radiant.",
    pricing_factors: [
      ["Surface et hauteur", "Détermine le nombre et puissance d'émetteurs."],
      ["Zonage", "Postes fixes ou circulation."],
      ["Type d'émetteur", "Tubes gaz vs panneaux IR haute température."],
      ["Raccordement gaz", "Réseau existant ou à créer."],
    ],
    faq_h2: "Questions sur le chauffage radiant.",
    faqs: [
      ["Tube radiant ou aérotherme ?", "Le radiant est plus économique en grand volume mal isolé ou en zone semi-ouverte. L'aérotherme reste pertinent en local fermé bien isolé."],
      ["Le radiant est-il sûr en milieu humide ?", "Oui à condition de respecter les distances de sécurité aux matières combustibles et de qualifier l'environnement (atmosphère, ATEX)."],
      ["Quelle hauteur minimale pour un tube radiant ?", "3,5 m sous le plus bas point d'émission. Pour les panneaux IR haute température, 4 à 6 m selon puissance."],
      ["Peut-on chauffer une zone ouverte ?", "Oui — c'est même un cas d'usage privilégié, en quai de chargement, terrasse couverte, halle ouverte."],
      ["Quelle économie vs chauffage classique ?", "−40 à −60% en moyenne, par effet zoning + absence de pertes par stratification."],
    ],
    cta_h2: "Un projet de chauffage radiant ? Parlons-en.",
  },
  {
    slug: "maintenance-chaufferie",
    path: "/chauffage-industriel/maintenance-chaufferie/",
    nav: "Maintenance chaufferie",
    breadcrumb: "Maintenance chaufferie",
    h1: "Maintenance chaufferie industrielle — contrats P1, P2, P3.",
    title: "Maintenance Chaufferie Industrielle — Contrat et Dépannage",
    metaDesc: "Contrats de maintenance P1/P2/P3 pour chaufferies industrielles, tertiaires et collectives. Astreinte 24/7 en Essonne et Loiret.",
    keyword: "maintenance chaufferie industrielle",
    icon: "wrench",
    lead: "Contrats d'exploitation et de maintenance de chaufferies industrielles et tertiaires. Garantie totale, dépannage 24/7, optimisation énergétique continue.",
    heroPhoto: "PHOTO TECHNICIEN EN MAINTENANCE",
    intro_h2: "La maintenance, première source d'économies.",
    def_h2: "Que couvre un contrat P1/P2/P3 ?",
    def_body: "P1 = fourniture de combustible. P2 = conduite, surveillance, entretien courant. P3 = grosses réparations et garantie totale du matériel. Notre métier : P2 et P3, parfois P1 selon vos besoins.",
    def_features: [
      "P2 — Conduite, entretien, sécurités",
      "P3 — Garantie totale matériel",
      "Astreinte 24/7 sur sites sensibles",
      "Reporting énergétique mensuel",
    ],
    schema_label: "SCHÉMA P1 / P2 / P3\n(qui fait quoi · responsabilités)",
    benefits_h2: "Les avantages d'un contrat de maintenance.",
    benefits: [
      ["clock", "Disponibilité maximale", "Astreinte 24/7 sur les sites critiques."],
      ["chart", "Économies continues", "Optimisation des consommations en continu."],
      ["shield", "Sécurité réglementaire", "Visites obligatoires assurées."],
      ["wrench", "Garantie totale matériel", "P3 = aucune mauvaise surprise budgétaire."],
      ["award", "Reporting transparent", "Tableaux de bord mensuels énergie."],
      ["users", "Interlocuteur dédié", "Un référent technique unique."],
    ],
    buildings: ["Industries", "Hôpitaux et cliniques", "Établissements scolaires", "Bâtiments tertiaires", "Logements collectifs", "Centres commerciaux", "Mairies", "ERP", "Sites multi-techniques"],
    process_h2: "Notre processus de prise en charge.",
    process: ["État des lieux et audit installation", "Définition du périmètre P1/P2/P3", "Contractualisation et reprise", "Suivi continu et reporting"],
    brands: ["Toutes marques", "Frisquet", "Viessmann", "De Dietrich", "Atlantic", "Bosch"],
    case_h3: "Contrat P3 — campus universitaire Évry.",
    case_body: "Reprise du contrat de maintenance de 4 chaufferies gaz totalisant 3 200 kW. Astreinte 24/7, garantie totale, reporting mensuel énergie.",
    case_metrics: [["Puissance suivie", "3 200 kW"], ["Disponibilité", "99,8%"], ["Économies an 1", "−18%"], ["Interventions / an", "32"]],
    pricing_h2: "Comment se construit votre contrat.",
    pricing_factors: [
      ["Périmètre P2 / P3", "Étendue des prestations couvertes."],
      ["Niveau d'astreinte", "Heures ouvrées, 24/7, GTR garanti."],
      ["Âge et état du parc", "Matériel récent vs vieillissant."],
      ["Reporting et GTB", "Niveau de digitalisation souhaité."],
    ],
    faq_h2: "Questions sur la maintenance chaufferie.",
    faqs: [
      ["Quelle différence entre P2 et P3 ?", "P2 = conduite, entretien et petits travaux. P3 = garantie totale matériel : remplacements et grosses réparations à notre charge."],
      ["Faut-il un contrat pour une chaudière < 70 kW ?", "Oui — la visite annuelle obligatoire (décret 2009) impose un professionnel qualifié, même hors ICPE."],
      ["Comment fonctionne la garantie totale ?", "Le P3 inclut le remplacement des composants en panne (échangeur, brûleur, circulateur) sans facturation supplémentaire, pendant toute la durée du contrat."],
      ["Astreinte 24/7 : à quel coût ?", "Comptez +15 à +25% sur le P2 selon la criticité du site et la fréquence d'intervention attendue. Devis sur mesure."],
      ["Puis-je changer de mainteneur en cours de contrat ?", "Oui à l'échéance ou avec préavis. Nous reprenons aussi les contrats existants après audit gratuit."],
    ],
    cta_h2: "Un parc à entretenir ? Discutons-en.",
  },
  {
    slug: "chauffage-collectif",
    path: "/chauffage-industriel/chauffage-collectif/",
    nav: "Chauffage collectif",
    breadcrumb: "Chauffage collectif",
    h1: "Chauffage collectif — copropriétés, mairies, écoles.",
    title: "Chauffage Collectif — Installation et Gestion de Chaufferies",
    metaDesc: "Conception et exploitation de chauffage collectif (copros, mairies, écoles) : chaudières gaz cascade, sous-stations, individualisation, mise en conformité.",
    keyword: "chauffage collectif",
    icon: "users",
    lead: "Conception, rénovation et exploitation de chauffages collectifs : chaudières gaz cascade, sous-stations, individualisation, mise en conformité décret tertiaire.",
    heroPhoto: "PHOTO IMMEUBLE / SOUS-STATION",
    intro_h2: "Chauffage collectif : performance et équité.",
    def_h2: "Qu'est-ce qu'un chauffage collectif ?",
    def_body: "Production centralisée distribuant la chaleur à plusieurs logements ou locaux. Concerne copropriétés, immeubles publics, écoles, mairies, bâtiments tertiaires multi-occupants.",
    def_features: [
      "Chaudières cascade gaz à condensation",
      "Sous-stations et réseaux secondaires",
      "Individualisation des frais (RFC)",
      "Pilotage GTB et suivi conso",
    ],
    schema_label: "SCHÉMA RÉSEAU COLLECTIF\n(production · primaire · sous-stations · logements)",
    benefits_h2: "Les avantages d'un chauffage collectif optimisé.",
    benefits: [
      ["chart", "Économies d'échelle", "Coût au m² inférieur à l'individuel."],
      ["users", "Confort homogène", "Tous les logements traités équitablement."],
      ["flame", "Décarbonation possible", "Biomasse, PAC, réseau de chaleur."],
      ["shield", "Conformité décret tertiaire", "Trajectoire −40% à 2030."],
      ["award", "Aides MaPrimeRénov' Copro", "Financements significatifs."],
      ["wrench", "Maintenance mutualisée", "Un seul contrat pour tout l'immeuble."],
    ],
    buildings: ["Copropriétés", "Logement social", "Écoles primaires et collèges", "Lycées", "Mairies", "Casernes", "Hôpitaux", "Résidences seniors", "Bâtiments tertiaires multi-locataires"],
    process_h2: "Notre processus chauffage collectif.",
    process: ["Audit énergétique du bâtiment", "Schéma directeur et scénarios", "Travaux et mise en service", "Exploitation et suivi conso"],
    brands: ["De Dietrich", "Viessmann", "Atlantic Guillot", "Frisquet", "Bosch", "Hoval"],
    case_h3: "Rénovation chauffage collectif — copro 84 logements Massy.",
    case_body: "Remplacement chaudière fioul 1985 par cascade gaz à condensation 380 kW + équilibrage réseau + individualisation des frais.",
    case_metrics: [["Logements", "84"], ["Puissance", "380 kW"], ["Économies / an", "−43%"], ["Aides", "92 000 €"]],
    pricing_h2: "Comment se construit votre devis collectif.",
    pricing_factors: [
      ["Audit existant", "État chaudière, réseau, émetteurs."],
      ["Nombre de points livrés", "Logements, sous-stations."],
      ["Énergie cible", "Gaz, PAC, réseau urbain, biomasse."],
      ["Individualisation RFC", "Comptage par logement obligatoire."],
    ],
    faq_h2: "Questions sur le chauffage collectif.",
    faqs: [
      ["Suis-je concerné par le décret tertiaire ?", "Oui pour tout bâtiment tertiaire de plus de 1 000 m². Trajectoire de −40% en 2030, −50% en 2040, −60% en 2050."],
      ["Individualisation des frais : obligatoire ?", "Oui dans les copropriétés équipées de chauffage collectif quand techniquement possible et économiquement viable, sauf dérogation."],
      ["Quel délai pour une rénovation copro ?", "6 à 18 mois entre la décision en AG et la mise en service, selon ampleur des travaux et obtention des aides."],
      ["Quelles aides pour le collectif ?", "MaPrimeRénov' Copro, CEE bonifiés, éco-PTZ collectif, fonds chaleur ADEME selon la solution choisie."],
      ["Peut-on passer en pompe à chaleur collective ?", "Oui — PAC air/eau ou eau/eau collective, souvent en hybride avec une chaudière gaz d'appoint pour les pointes."],
    ],
    cta_h2: "Un projet collectif ? Parlons-en.",
  },
  {
    slug: "chauffage-electrique-collectif",
    path: "/chauffage-industriel/chauffage-electrique-collectif/",
    nav: "Chauffage électrique collectif",
    breadcrumb: "Chauffage électrique collectif",
    h1: "Chauffage électrique collectif — alternatives et rénovation.",
    title: "Chauffage Électrique Collectif — Solutions et Alternatives",
    metaDesc: "Conversion de chauffages électriques collectifs vers PAC, hybride ou réseau de chaleur. Audit, scénarios chiffrés, montage des aides.",
    keyword: "chauffage électrique collectif",
    icon: "bolt",
    lead: "Audit, optimisation et conversion de chauffages électriques collectifs : pompes à chaleur, hybrides, raccordement aux réseaux de chaleur. Sortie progressive de l'effet Joule.",
    heroPhoto: "PHOTO ANCIEN CONVECTEUR / PAC NEUVE",
    intro_h2: "Sortir de l'effet Joule, pas à pas.",
    def_h2: "Pourquoi rénover un chauffage électrique ?",
    def_body: "Les convecteurs et planchers chauffants électriques sont énergivores et difficiles à amortir. Le décret tertiaire impose une réduction des consommations qui passe presque toujours par une bascule technologique.",
    def_features: [
      "Pompes à chaleur air/eau et air/air",
      "Solutions hybrides PAC + appoint",
      "Raccordement réseaux de chaleur",
      "Suivi conso post-bascule",
    ],
    schema_label: "SCHÉMA TRAJECTOIRE\n(état initial électrique · scénarios · cible décarbonée)",
    benefits_h2: "Les avantages de la conversion.",
    benefits: [
      ["chart", "Jusqu'à −70% conso", "Une PAC consomme 3 à 4× moins."],
      ["flame", "Décarbonation", "Réduction massive de l'empreinte carbone."],
      ["shield", "Décret tertiaire", "Trajectoire compatible −40% à 2030."],
      ["award", "Aides cumulées", "MaPrimeRénov', CEE, fonds chaleur ADEME."],
      ["thermo", "Confort accru", "Chaleur douce, pilotage fin."],
      ["users", "Acceptation copro", "Argumentaire chiffré pour AG."],
    ],
    buildings: ["Copropriétés tout électrique", "Logements sociaux", "Écoles", "Bureaux tertiaires", "Hôtels et résidences", "EHPAD", "Centres de loisirs", "ERP", "Bâtiments des années 70-80"],
    process_h2: "Notre processus de conversion.",
    process: ["Audit énergétique et bilan carbone", "Étude de scénarios chiffrés", "Travaux et bascule progressive", "Suivi consos et ajustements"],
    brands: ["Daikin", "Mitsubishi", "Atlantic", "Stiebel Eltron", "Hitachi", "Panasonic"],
    case_h3: "Conversion électrique → PAC — résidence Corbeil.",
    case_body: "Remplacement convecteurs électriques par PAC air/eau collective 240 kW + ballons tampons + comptage par logement, sur 64 logements.",
    case_metrics: [["Logements", "64"], ["Conso élec", "−68%"], ["CO₂", "−74%"], ["Aides perçues", "184 000 €"]],
    pricing_h2: "Comment se construit votre devis conversion.",
    pricing_factors: [
      ["Configuration bâti", "Maillage électrique, possibilité d'eau chaude."],
      ["Solution cible", "PAC monobloc, multi-split, hybride."],
      ["Réseau secondaire à créer", "Tuyauterie, émetteurs."],
      ["Lots tests vs full", "Approche progressive ou globale."],
    ],
    faq_h2: "Questions sur la conversion électrique.",
    faqs: [
      ["Peut-on garder les convecteurs en appoint ?", "Oui en solution hybride : PAC majoritaire + convecteurs pour les pointes. Optimise l'investissement initial."],
      ["Quel délai pour une copropriété ?", "12 à 24 mois en moyenne — études, AG, montage des aides, travaux. La bascule peut être progressive (lot tests d'abord)."],
      ["Faut-il une AG spécifique ?", "Oui — vote en AG des travaux, accompagné d'un dossier technique et financier détaillé. Nous fournissons le matériel d'argumentation."],
      ["Quelles aides cumulables ?", "MaPrimeRénov' Copro + CEE + éco-PTZ + parfois aides régionales. Cumul fréquent jusqu'à 50% du montant des travaux."],
      ["Combien de temps pour amortir ?", "8 à 12 ans en moyenne, selon le delta de consommation et les aides obtenues. Calcul précis dans l'étude."],
    ],
    cta_h2: "Sortir de l'effet Joule ? Étudions ensemble.",
  },
];

const SISTERS = SERVICES_INDUSTRIEL.map(s => [s.nav, s.path, s.icon]);

// ---------- Local pages: chauffage industriel par département ----------
const LOCAL_INDUS = [
  {
    slug: "chauffage-industriel-essonne",
    path: "/chauffage-industriel-essonne/",
    breadcrumb: "Chauffage industriel Essonne",
    h1: "Chauffage industriel en Essonne (91).",
    title: "Chauffage Industriel en Essonne (91) | Plomberie Services 91",
    metaDesc: "Chauffagiste industriel en Essonne (91) : installation, maintenance et dépannage de chaufferies, aérothermes, radiants. Étampes, Évry, Les Ulis.",
    keyword: "chauffage industriel essonne",
    department: "91",
    region: "Essonne",
    cities: ["Étampes", "Dourdan", "Pussay", "Milly-la-Forêt", "Arpajon", "Brétigny", "Évry", "Les Ulis", "Massy", "Palaiseau", "Saclay", "Corbeil-Essonnes", "Saint-Michel-sur-Orge"],
    zones: ["ZI Brières-les-Scellés", "ZI Morangis", "ZI Les Ulis", "ZI Villebon", "ZI La Croix Blanche"],
    intro: "L'Essonne concentre une activité industrielle dense — sites logistiques, biotechs Saclay, ateliers PME, chaufferies de copropriétés. Plomberie Services 91 intervient sur l'ensemble du département pour la conception, la rénovation et la maintenance de chauffages industriels et collectifs.",
  },
  {
    slug: "chauffage-industriel-loiret",
    path: "/chauffage-industriel-loiret/",
    breadcrumb: "Chauffage industriel Loiret",
    h1: "Chauffage industriel dans le Loiret (45).",
    title: "Chauffage Industriel dans le Loiret (45) | Plomberie Services 91",
    metaDesc: "Chauffagiste industriel Loiret (45) : chaufferies, aérothermes, radiants, maintenance P1/P2/P3. Orléans, Pithiviers, Montargis.",
    keyword: "chauffage industriel loiret",
    department: "45",
    region: "Loiret",
    cities: ["Orléans", "Pithiviers", "Montargis", "Gien", "Beaugency", "Olivet", "Saran", "Fleury-les-Aubrais", "Saint-Jean-de-Braye", "Châlette-sur-Loing", "Oison"],
    zones: ["ZI Saran", "ZAC du Clos du Roy", "ZAC Pôle 45", "ZI Gien", "ZI Pithiviers"],
    intro: "Le Loiret accueille de nombreux sites industriels : logistique Saran, cosmétiques, agroalimentaire Pithiviers, hôpitaux et collectivités. Notre équipe basée à Oison intervient quotidiennement sur l'ensemble du département.",
  },
];

// ---------- Hub Chauffagiste + locales ----------
const SERVICES_CHAUFFAGISTE = [
  {
    slug: "chauffagiste-essonne",
    path: "/chauffagiste-essonne/",
    breadcrumb: "Chauffagiste Essonne",
    h1: "Chauffagiste en Essonne (91) — devis gratuit.",
    title: "Chauffagiste en Essonne (91) — Devis Gratuit | Plomberie Services 91",
    metaDesc: "Chauffagiste qualifié en Essonne (91). Installation, maintenance, dépannage chauffage gaz, PAC, biomasse. Devis gratuit sous 24h.",
    keyword: "chauffagiste essonne",
    department: "91",
    region: "Essonne",
    cities: ["Étampes", "Dourdan", "Pussay", "Arpajon", "Évry", "Les Ulis", "Massy", "Palaiseau", "Brétigny", "Corbeil-Essonnes"],
    intro: "Plomberie Services 91 est votre chauffagiste de proximité en Essonne. Particuliers, copropriétés, sites industriels — nous intervenons sur tous types de chauffage : gaz, fioul, biomasse, pompe à chaleur.",
  },
  {
    slug: "chauffagiste-loiret",
    path: "/chauffagiste-loiret/",
    breadcrumb: "Chauffagiste Loiret",
    h1: "Chauffagiste dans le Loiret (45) — installation et dépannage.",
    title: "Chauffagiste dans le Loiret (45) — Installation et Dépannage",
    metaDesc: "Chauffagiste certifié dans le Loiret (45). Installation, dépannage et entretien chauffage gaz, biomasse, PAC. Orléans, Pithiviers, Montargis.",
    keyword: "chauffagiste loiret",
    department: "45",
    region: "Loiret",
    cities: ["Orléans", "Pithiviers", "Montargis", "Gien", "Beaugency", "Olivet", "Oison"],
    intro: "Implantés à Oison (45170), nous sommes votre chauffagiste de référence sur le Loiret. Conception, rénovation, maintenance — pour particuliers, collectivités et industriels.",
  },
];

// ---------- Devis pages ----------
const DEVIS_PAGES = [
  {
    slug: "devis-chauffage-industriel",
    path: "/devis-chauffage-industriel/",
    breadcrumb: "Devis chauffage industriel",
    h1: "Devis chauffage industriel gratuit — réponse sous 24h.",
    title: "Devis Chauffage Industriel Gratuit — Réponse sous 24h",
    metaDesc: "Demandez un devis chauffage industriel gratuit en Essonne, Loiret et IDF. Réponse sous 24h, sans engagement, par un chauffagiste certifié.",
    keyword: "devis chauffage industriel",
    intro: "Plomberie Services 91 vous fournit un devis chauffage industriel détaillé sous 24h ouvrées. Étude personnalisée, dimensionnement, choix d'énergie, mise en conformité ICPE — tout est compris.",
    pillars: [
      ["Réponse sous 24h ouvrées", "Visite sur site programmée sous 5 jours."],
      ["Étude personnalisée", "Aucun chiffrage forfaitaire — chaque site a son propre dimensionnement."],
      ["Sans engagement", "Devis gratuit, vous restez libre de votre choix."],
      ["Aides intégrées", "Nous indiquons les CEE, aides ADEME et MaPrimeRénov' applicables."],
    ],
  },
  {
    slug: "devis-chauffagiste",
    path: "/devis-chauffagiste/",
    breadcrumb: "Devis chauffagiste",
    h1: "Devis chauffagiste gratuit — Essonne, Loiret, Île-de-France.",
    title: "Devis Chauffagiste Gratuit — Essonne, Loiret, Île-de-France",
    metaDesc: "Devis chauffagiste gratuit pour installation, dépannage ou maintenance. Essonne, Loiret et toute l'Île-de-France. Réponse sous 24h.",
    keyword: "devis chauffagiste",
    intro: "Particuliers, copropriétés, professionnels : recevez gratuitement un devis chauffagiste sous 24h. Nous étudions votre besoin, dimensionnons la solution et vous proposons un chiffrage clair.",
    pillars: [
      ["Devis sous 24h", "Réponse rapide pour les chantiers urgents."],
      ["Tous chauffages", "Gaz, fioul, électrique, PAC, biomasse, granulés."],
      ["Toutes échelles", "Particulier, copropriété, industriel."],
      ["Certifié RGE", "Pour bénéficier des aides énergétiques."],
    ],
  },
  {
    slug: "devis-installation-chauffage",
    path: "/devis-installation-chauffage/",
    breadcrumb: "Devis installation chauffage",
    h1: "Devis installation chauffage — gaz, électrique, biomasse.",
    title: "Devis Installation Chauffage — Gaz, Électrique, Biomasse",
    metaDesc: "Devis installation chauffage gratuit : chaudière gaz, PAC, biomasse, granulés. Étude, dimensionnement et chiffrage précis sous 24h.",
    keyword: "devis installation chauffage",
    intro: "Vous remplacez une chaudière vieillissante ou équipez un bâtiment neuf ? Notre étude technique précise votre besoin, le dimensionnement, l'énergie cible et les coûts d'exploitation prévisionnels.",
    pillars: [
      ["Étude technique poussée", "Bilan thermique, profil de consommation, coûts annuels."],
      ["Toutes énergies", "Gaz, granulés, plaquettes, PAC, hybride, électrique direct."],
      ["Comparatif chiffré", "2 à 3 scénarios chiffrés pour décider en connaissance."],
      ["Mise en service incluse", "Réception, mise en main, formation utilisateur."],
    ],
  },
  {
    slug: "devis-depannage-chauffage",
    path: "/devis-depannage-chauffage/",
    breadcrumb: "Devis dépannage chauffage",
    h1: "Devis dépannage chauffage — intervention rapide.",
    title: "Devis Dépannage Chauffage — Intervention Rapide",
    metaDesc: "Devis dépannage chauffage gratuit, intervention rapide en Essonne et Loiret. Chaudière en panne, fuite, sécurité — réponse sous quelques heures.",
    keyword: "devis depannage chauffage",
    intro: "Panne de chaudière, alarme sécurité, débit insuffisant — nous intervenons rapidement et fournissons un devis de dépannage sous 24h. Astreinte 24/7 pour nos clients sous contrat.",
    pillars: [
      ["Intervention rapide", "Sous 4 à 24h selon criticité."],
      ["Diagnostic clair", "Cause de la panne, pièces concernées, alternatives."],
      ["Devis avant travaux", "Aucune surprise — vous validez avant intervention."],
      ["Pièces toutes marques", "Stock atelier sur les marques majeures."],
    ],
  },
  {
    slug: "devis-maintenance-chauffage",
    path: "/devis-maintenance-chauffage/",
    breadcrumb: "Devis maintenance chauffage",
    h1: "Devis maintenance chauffage — contrat entretien pro.",
    title: "Devis Maintenance Chauffage — Contrat Entretien Pro",
    metaDesc: "Devis contrat de maintenance chauffage : P1, P2, P3 pour chaufferies industrielles, tertiaires, collectives. Astreinte 24/7 disponible.",
    keyword: "devis maintenance chauffage",
    intro: "Votre installation mérite un contrat de maintenance dimensionné à votre criticité. Nous vous proposons un contrat P1/P2/P3 sur-mesure, adapté à votre parc et à votre budget.",
    pillars: [
      ["Audit gratuit", "État des lieux complet de votre installation."],
      ["Périmètre modulaire", "P2, P3 ou les deux — vous choisissez."],
      ["Astreinte 24/7", "Pour les sites critiques."],
      ["Reporting mensuel", "Tableau de bord énergie + interventions."],
    ],
  },
  {
    slug: "devis-plombier-chauffagiste",
    path: "/devis-plombier-chauffagiste/",
    breadcrumb: "Devis plombier chauffagiste",
    h1: "Devis plombier chauffagiste gratuit.",
    title: "Devis Plombier Chauffagiste Gratuit — Plomberie Services 91",
    metaDesc: "Devis gratuit plombier chauffagiste pour particuliers et professionnels en Essonne et Loiret. Plomberie, chauffage, sanitaire, dépannage.",
    keyword: "devis plombier chauffagiste",
    intro: "Plomberie et chauffage : un seul interlocuteur. Devis gratuit pour vos travaux de plomberie, sanitaire, chauffage, dépannage. Particuliers comme professionnels.",
    pillars: [
      ["Plomberie + chauffage", "Une seule entreprise pour tout votre projet."],
      ["Particulier ou pro", "Adapté à votre échelle de besoin."],
      ["Pose ou rénovation", "Construction neuve, rénovation, dépannage."],
      ["Tarifs transparents", "Forfait main d'œuvre annoncé en amont."],
    ],
  },
  {
    slug: "devis-chauffagiste-essonne",
    path: "/devis-chauffagiste-essonne/",
    breadcrumb: "Devis chauffagiste Essonne",
    h1: "Devis chauffagiste en Essonne (91) — gratuit sans engagement.",
    title: "Devis Chauffagiste en Essonne (91) — Gratuit Sans Engagement",
    metaDesc: "Devis chauffagiste gratuit dans toute l'Essonne. Réponse rapide, intervention sur Étampes, Évry, Les Ulis, Massy, Palaiseau.",
    keyword: "devis chauffagiste essonne",
    intro: "Chauffagiste local en Essonne, nous fournissons un devis gratuit sous 24h pour tous types d'installation : chaudière gaz, PAC, biomasse, chauffage industriel.",
    pillars: [
      ["Couverture 91 complète", "Étampes, Évry, Massy, Les Ulis, Brétigny."],
      ["Devis sous 24h", "Étude rapide pour décider vite."],
      ["Tous bâtiments", "Maison, copropriété, site industriel."],
      ["Aides incluses", "MaPrimeRénov', CEE, ADEME."],
    ],
  },
  {
    slug: "devis-chauffagiste-loiret",
    path: "/devis-chauffagiste-loiret/",
    breadcrumb: "Devis chauffagiste Loiret",
    h1: "Devis chauffagiste dans le Loiret (45) — gratuit.",
    title: "Devis Chauffagiste dans le Loiret (45) — Gratuit",
    metaDesc: "Devis chauffagiste gratuit dans le Loiret. Orléans, Pithiviers, Montargis, Gien — installation, maintenance, dépannage.",
    keyword: "devis chauffagiste loiret",
    intro: "Implantés à Oison, nous proposons un devis chauffagiste gratuit dans tout le Loiret. Particuliers, collectivités, industriels : un seul interlocuteur.",
    pillars: [
      ["Couverture 45 complète", "Orléans, Pithiviers, Montargis, Gien."],
      ["Réponse sous 24h", "Devis rapide pour les chantiers urgents."],
      ["Toutes énergies", "Gaz, granulés, fioul, PAC, hybride."],
      ["Aides MaPrimeRénov'", "Montage des dossiers inclus."],
    ],
  },
  {
    slug: "devis-chauffagiste-ile-de-france",
    path: "/devis-chauffagiste-ile-de-france/",
    breadcrumb: "Devis chauffagiste Île-de-France",
    h1: "Devis chauffagiste Île-de-France — gratuit sans engagement.",
    title: "Devis Chauffagiste Île-de-France — Gratuit Sans Engagement",
    metaDesc: "Devis chauffagiste gratuit en Île-de-France. Chauffage industriel, copropriétés, particuliers — Paris, 91, 92, 93, 94, 95, 77, 78.",
    keyword: "devis chauffagiste ile de france",
    intro: "Notre équipe se déplace dans toute l'Île-de-France pour les projets industriels et collectifs. Devis gratuit sous 24h, étude technique sur site.",
    pillars: [
      ["IDF complète", "Paris + 91, 92, 93, 94, 95, 77, 78."],
      ["Industriel / collectif", "Spécialisés sur les projets multi-techniques."],
      ["Études certifiées RGE", "Pour bénéficier de toutes les aides."],
      ["Maintenance ensuite", "Contrats P2/P3 si besoin de continuité."],
    ],
  },
];

// ---------- Blog ----------
const BLOG_HUBS = [
  {
    slug: "chauffage-industriel",
    path: "/blog/chauffage-industriel/",
    h1: "Blog chauffage industriel — guides pro.",
    title: "Blog Chauffage Industriel — Guides Pro",
    metaDesc: "Articles, guides et études techniques sur le chauffage industriel : ICPE, décret tertiaire, comparatifs énergies, dimensionnement.",
    parentService: "/chauffagiste-industriel/",
  },
  {
    slug: "chauffagiste",
    path: "/blog/chauffagiste/",
    h1: "Blog chauffagiste — conseils et expertise.",
    title: "Blog Chauffagiste — Conseils et Expertise",
    metaDesc: "Conseils, comparatifs et guides du métier de chauffagiste : choisir un pro, dépannage, contrats, certifications.",
    parentService: "/chauffagiste/",
  },
];

const BLOG_ARTICLES = [
  // Chauffage industriel
  {
    slug: "chauffer-batiment-industriel",
    hub: "chauffage-industriel",
    path: "/blog/chauffage-industriel/chauffer-batiment-industriel/",
    title: "Comment chauffer un bâtiment industriel ? | Guide Plomberie Services 91",
    h1: "Comment chauffer un bâtiment industriel ?",
    metaDesc: "Guide complet pour chauffer un bâtiment industriel : technologies, dimensionnement, énergies, aides. Comparatif aérotherme / radiant / chaufferie.",
    keyword: "chauffage batiment industriel",
    excerpt: "Aérotherme, radiant, chaufferie centralisée : quelle solution pour votre bâtiment industriel ? Comparatif des technologies et critères de choix.",
    intro: "Choisir un chauffage industriel est rarement une décision simple. Volume, hauteur, isolation, occupation, énergie disponible : chaque paramètre oriente vers une technologie. Voici un guide structuré pour vous y retrouver.",
    sections: [
      ["Évaluer son besoin thermique", "Le premier réflexe est de quantifier le besoin : surface, hauteur sous plafond, isolation des parois et de la toiture, infiltrations d'air, nombre d'occupants, mode d'occupation (continue ou intermittente). Un bilan thermique sommaire donne déjà une fourchette de puissance."],
      ["Les trois grandes familles de solutions", "On distingue : 1) le chauffage centralisé via une chaufferie alimentant des aérothermes hydrauliques ou un réseau de panneaux ; 2) le chauffage décentralisé par aérothermes gaz ; 3) le chauffage radiant — tubes ou panneaux infrarouges. Chacune a son domaine de pertinence."],
      ["Aérotherme ou radiant ?", "L'aérotherme convient en local fermé bien isolé avec occupation prolongée. Le radiant prend l'avantage en grande hauteur, en occupation intermittente, et même en zone semi-ouverte (quai, hall, atelier mal isolé)."],
      ["Quel combustible ?", "Le gaz reste l'énergie de référence en industrie pour son coût et sa puissance. La biomasse (granulés, plaquettes) progresse, surtout pour les sites engagés dans la décarbonation. La PAC haute température arrive sur les puissances moyennes (50–500 kW)."],
      ["Conformité ICPE et décret tertiaire", "Au-delà de 70 kW, la rubrique ICPE 2910 s'applique. Le décret tertiaire impose une trajectoire de baisse des consommations pour les bâtiments tertiaires de plus de 1 000 m². Anticiper ces deux contraintes en amont du projet est crucial."],
      ["Aides et financements", "CEE, fonds chaleur ADEME, MaPrimeRénov' Copro, FEDER : la plupart des projets industriels sont éligibles à au moins une aide. Cumuls fréquents jusqu'à 30–50% du montant des travaux."],
    ],
    relatedServices: ["aerotherme", "chauffage-radiant", "chauffage-hangar", "chaufferie-industrielle"],
    publishedDate: "2026-04-12",
  },
  {
    slug: "normes-chaufferie",
    hub: "chauffage-industriel",
    path: "/blog/chauffage-industriel/normes-chaufferie/",
    title: "Normes chaufferie industrielle 2026 : ICPE, ATEX, sécurités",
    h1: "Normes chaufferie industrielle 2026.",
    metaDesc: "Le point complet sur les normes applicables aux chaufferies industrielles en 2026 : ICPE 2910, 2921, ATEX, sécurités gaz, désenfumage.",
    keyword: "normes chaufferie industrielle",
    excerpt: "ICPE 2910, 2921, ATEX, sécurités gaz : guide complet des normes applicables aux chaufferies industrielles en 2026.",
    intro: "Mettre en conformité une chaufferie industrielle est un parcours réglementaire dense. Cinq cadres principaux se superposent — ICPE, ATEX, code du travail, sécurité incendie, décret tertiaire.",
    sections: [
      ["ICPE 2910 — combustion", "Tout équipement de combustion supérieur à 1 MW est soumis à enregistrement. Entre 0,1 et 1 MW, c'est une déclaration. La rubrique encadre l'implantation, les sécurités et la surveillance."],
      ["ICPE 2921 — refroidissement", "Tours aéroréfrigérantes humides (légionellose) : déclaration ou enregistrement selon puissance. Surveillance microbiologique et plan de gestion obligatoires."],
      ["Réglementation ATEX", "Les zones où peuvent se former des atmosphères explosives sont classées et signalées. Les équipements doivent être adaptés à la zone."],
      ["Sécurités gaz", "Détection gaz, électrovanne, ventilation haute et basse, contrôle d'étanchéité — exigences détaillées dans l'arrêté ministériel."],
      ["Décret tertiaire 2027", "Pour les bâtiments tertiaires > 1 000 m² : reporting OPERAT et trajectoire −40% à 2030. La chaufferie est souvent le levier principal."],
    ],
    relatedServices: ["chaufferie-industrielle", "chauffage-gaz", "maintenance-chaufferie"],
    publishedDate: "2026-03-24",
  },
  {
    slug: "gaz-vs-electrique",
    hub: "chauffage-industriel",
    path: "/blog/chauffage-industriel/gaz-vs-electrique/",
    title: "Chauffage gaz vs électrique en industrie : comparatif 2026",
    h1: "Chauffage gaz vs électrique en industrie.",
    metaDesc: "Comparatif détaillé chauffage gaz vs électrique en milieu industriel : coûts, émissions, performances, conformité décret tertiaire.",
    keyword: "chauffage gaz industriel",
    excerpt: "Coût d'exploitation, conformité décret tertiaire, décarbonation : le comparatif complet entre chauffage gaz et électrique pour l'industrie.",
    intro: "La question revient à chaque projet : faut-il rester au gaz ou passer à l'électrique (PAC) ? La réponse dépend de cinq facteurs — puissance, profil de consommation, énergie disponible, contrainte décret tertiaire, et bilan carbone visé.",
    sections: [
      ["Coût d'exploitation", "Le gaz reste compétitif sur les fortes puissances et les régimes continus. La PAC, avec un COP de 3 à 4, divise la consommation primaire mais l'électron est plus cher au kWh."],
      ["Performances et puissance", "Le gaz adresse facilement plusieurs MW. La PAC plafonne autour de 1 MW en haute température, mais s'étend rapidement avec les nouvelles générations."],
      ["Émissions CO₂", "Une PAC est 3 à 4× moins émissive que le gaz, surtout avec le mix électrique français. C'est l'argument central du décret tertiaire."],
      ["Conformité décret tertiaire", "Atteindre −40% en 2030 sans bascule vers la PAC ou la biomasse devient difficile pour la plupart des sites tertiaires."],
      ["Hybridation : la voie médiane", "Beaucoup d'industriels optent pour l'hybride : PAC en base + chaudière gaz en pointe. C'est souvent le meilleur compromis technico-économique."],
    ],
    relatedServices: ["chauffage-gaz", "chauffage-electrique-collectif", "chaufferie-industrielle"],
    publishedDate: "2026-03-10",
  },
  {
    slug: "prix-installation",
    hub: "chauffage-industriel",
    path: "/blog/chauffage-industriel/prix-installation/",
    title: "Prix installation chaufferie industrielle : à quoi s'attendre",
    h1: "Prix installation chaufferie industrielle.",
    metaDesc: "Tout savoir sur le prix d'une chaufferie industrielle en 2026 : facteurs, fourchettes, ratios, aides applicables.",
    keyword: "prix chaufferie industrielle",
    excerpt: "Quels sont les ratios de prix pour une chaufferie industrielle en 2026 ? Facteurs de coût, fourchettes par puissance, aides ADEME et CEE.",
    intro: "Donner un prix à une chaufferie industrielle hors étude est un mauvais service. Mais on peut donner des ratios et des fourchettes utiles pour cadrer un budget initial.",
    sections: [
      ["Les variables qui pèsent le plus", "Puissance installée, redondance souhaitée, énergie cible, niveau de GTB, état de l'existant. À puissance égale, le coût peut varier d'un facteur 2."],
      ["Ratios indicatifs gaz", "Comptez 250 à 500 €/kW HT pour une chaufferie gaz à condensation cascade neuve, hors raccordements et terrassement."],
      ["Ratios indicatifs biomasse", "1 200 à 2 500 €/kW HT pour une chaufferie biomasse complète avec silo et logistique. Coût initial élevé, exploitation économique."],
      ["Coûts annexes à ne pas oublier", "Génie civil (silo biomasse), raccordements gaz/électrique, GTB, désenfumage, mises en conformité — souvent 20 à 40% du budget total."],
      ["Aides mobilisables", "Fonds chaleur ADEME (jusqu'à 50% pour la biomasse), CEE bonifiés, MaPrimeRénov' Copro pour le résidentiel collectif. Cumuls fréquents."],
    ],
    relatedServices: ["chaufferie-industrielle", "chauffage-gaz"],
    publishedDate: "2026-02-22",
  },
  {
    slug: "maintenance-preventive",
    hub: "chauffage-industriel",
    path: "/blog/chauffage-industriel/maintenance-preventive/",
    title: "Maintenance préventive chaufferie : pourquoi et comment",
    h1: "Maintenance préventive chaufferie.",
    metaDesc: "Maintenance préventive de chaufferie industrielle : points de contrôle, périodicité, économies réalisées, contrats P2 et P3.",
    keyword: "maintenance chaufferie",
    excerpt: "Pourquoi investir dans la maintenance préventive plutôt que curative ? Bénéfices chiffrés, points de contrôle et choix du contrat.",
    intro: "La maintenance préventive coûte 3 à 5× moins que la maintenance curative sur la durée de vie d'une chaufferie. Sans parler de la disponibilité.",
    sections: [
      ["Disponibilité maximale", "Une chaufferie suivie sort 99,5% du temps. Une chaufferie négligée tombe en panne au pire moment — souvent en pleine saison."],
      ["Points de contrôle clés", "Étanchéité gaz, sécurités, propreté brûleur, qualité de combustion, performance échangeur, équilibrage circulateurs, traitement d'eau."],
      ["Périodicité recommandée", "Visite annuelle obligatoire pour le réglementaire. Visites trimestrielles ou semestrielles recommandées pour les sites critiques."],
      ["P2 ou P3 ?", "Le P2 couvre la conduite et l'entretien. Le P3 ajoute la garantie totale matériel — plus cher mais sans surprise budgétaire."],
      ["Économies réalisables", "Une chaufferie bien réglée consomme 5 à 15% de moins. Sur un site qui consomme 100 000 €/an, c'est 5 000 à 15 000 € d'économies récurrentes."],
    ],
    relatedServices: ["maintenance-chaufferie", "chaufferie-industrielle"],
    publishedDate: "2026-02-08",
  },
  // Chauffagiste
  {
    slug: "choisir-chauffagiste-industriel",
    hub: "chauffagiste",
    path: "/blog/chauffagiste/choisir-chauffagiste-industriel/",
    title: "Comment choisir son chauffagiste industriel ?",
    h1: "Comment choisir son chauffagiste industriel ?",
    metaDesc: "Les 7 critères pour bien choisir un chauffagiste industriel : certifications, références, contrats, capacité, transparence.",
    keyword: "chauffagiste industriel",
    excerpt: "Certifications, références, contrats, transparence : les 7 critères qui distinguent un vrai chauffagiste industriel d'un installateur généraliste.",
    intro: "Confier sa chaufferie à un chauffagiste industriel n'a pas grand-chose à voir avec installer une chaudière chez un particulier. Voici les critères à vérifier.",
    sections: [
      ["Certifications spécifiques", "QualiGaz pour le gaz, RGE pour les aides, QualiPAC pour les pompes à chaleur, QualiBois pour la biomasse. Une station SEET est un plus pour les diagnostics constructeur."],
      ["Capacité à porter du P3", "Un vrai chauffagiste industriel propose des contrats P3 — c'est-à-dire qu'il s'engage sur la garantie matériel. Cela suppose une assise financière."],
      ["Références équivalentes", "Demandez 3 références sur des installations comparables en taille et complexité. Visitables si possible."],
      ["Capacité d'astreinte", "Pour un site critique, l'astreinte 24/7 est non-négociable. Vérifiez l'organisation, pas seulement la promesse."],
      ["Transparence sur le devis", "Pas de prix forfaitaires sortis du chapeau. Un bon devis explique le dimensionnement, le choix du matériel et les coûts d'exploitation prévisionnels."],
      ["Capacité au montage des aides", "CEE, ADEME, MaPrimeRénov' : un chauffagiste industriel sait constituer ces dossiers sans facturer une prestation séparée."],
      ["Pérennité de l'entreprise", "Une chaufferie a une durée de vie de 20–25 ans. Vous voulez un partenaire qui sera là dans 10 ans pour assurer le P3."],
    ],
    relatedServices: ["chaufferie-industrielle", "maintenance-chaufferie"],
    publishedDate: "2026-04-05",
  },
  {
    slug: "collectif-vs-individuel",
    hub: "chauffagiste",
    path: "/blog/chauffagiste/collectif-vs-individuel/",
    title: "Chauffage collectif vs individuel : avantages et limites",
    h1: "Chauffage collectif vs individuel.",
    metaDesc: "Comparatif chauffage collectif vs individuel pour copropriétés : coûts, équité, décarbonation, individualisation des frais.",
    keyword: "chauffage collectif ou individuel",
    excerpt: "Comparatif technico-économique entre chauffage collectif et individuel — pour les copropriétés qui hésitent ou doivent rénover.",
    intro: "La question revient toujours en AG : faut-il garder le chauffage collectif ou passer à l'individuel ? Tour d'horizon des arguments, sans dogme.",
    sections: [
      ["Coût d'investissement", "Le collectif est plus cher à mettre en place mais s'amortit sur l'ensemble du bâtiment. L'individuel fragmente les investissements."],
      ["Coût d'exploitation", "Le collectif bénéficie d'économies d'échelle : achat combustible groupé, entretien mutualisé. L'individuel laisse chaque foyer décider."],
      ["Équité entre logements", "Le collectif garantit le confort à tous. L'individuel laisse l'arbitrage au foyer — au risque de sous-chauffer certains logements."],
      ["Capacité de décarbonation", "Le collectif peut basculer en biomasse, PAC, réseau urbain — pas l'individuel. C'est un argument fort à l'heure du décret tertiaire."],
      ["Individualisation des frais (RFC)", "Obligatoire en collectif quand techniquement possible. Permet d'aligner facture et consommation réelle."],
    ],
    relatedServices: ["chauffage-collectif", "chauffage-electrique-collectif"],
    publishedDate: "2026-03-15",
  },
  {
    slug: "role-competences",
    hub: "chauffagiste",
    path: "/blog/chauffagiste/role-competences/",
    title: "Chauffagiste : rôle et compétences",
    h1: "Chauffagiste : rôle et compétences.",
    metaDesc: "Le métier de chauffagiste : missions, compétences, formations, certifications requises. Différences avec plombier et frigoriste.",
    keyword: "chauffagiste",
    excerpt: "Quelles sont les missions et compétences d'un chauffagiste ? Différences avec plombier et frigoriste, certifications, parcours.",
    intro: "Le métier de chauffagiste recouvre des réalités très diverses, du dépannage individuel à la conduite de chaufferies industrielles. Décryptage.",
    sections: [
      ["Le cœur du métier", "Concevoir, installer, entretenir et dépanner les systèmes de chauffage. Cela couvre les générateurs (chaudière, PAC, brûleur), les réseaux et les émetteurs."],
      ["Différence avec un plombier", "Le plombier traite les réseaux d'eau et le sanitaire. Le chauffagiste est spécialisé sur la production de chaleur. Beaucoup d'entreprises font les deux — d'où le 'plombier-chauffagiste'."],
      ["Différence avec un frigoriste", "Le frigoriste manipule les fluides frigorigènes (PAC, climatisation). Habilitation spécifique. Les compétences se croisent sur les PAC."],
      ["Certifications professionnelles", "QualiGaz, QualiPAC, QualiBois, RGE — selon les énergies traitées. La station SEET est un label fabricant."],
      ["Parcours de formation", "CAP MIT, BAC pro Maintenance, BTS FED — la formation initiale ouvre la voie. La formation continue est essentielle pour suivre les évolutions techniques."],
    ],
    relatedServices: ["chaufferie-industrielle", "maintenance-chaufferie"],
    publishedDate: "2026-02-15",
  },
  {
    slug: "depannage-chauffage",
    hub: "chauffagiste",
    path: "/blog/chauffagiste/depannage-chauffage/",
    title: "Dépannage chauffage : quand appeler un pro ?",
    h1: "Dépannage chauffage : quand appeler un pro.",
    metaDesc: "Quand appeler un chauffagiste pour dépannage ? Pannes courantes, diagnostic, premières actions, choix du professionnel.",
    keyword: "dépannage chauffage",
    excerpt: "Pannes courantes, premières actions à tenter, signaux d'alerte qui imposent l'appel à un pro — guide pratique.",
    intro: "Une chaudière qui ne démarre plus, des radiateurs froids, un code d'erreur cryptique : voici comment diagnostiquer rapidement et savoir quand appeler.",
    sections: [
      ["Vérifications de base", "Pression hydraulique, alimentation gaz/électricité, thermostat, code d'erreur affiché, purge des radiateurs. 30% des pannes se règlent ainsi."],
      ["Signaux d'alerte sérieux", "Odeur de gaz, monoxyde de carbone, fumée anormale, alarme sécurité — coupez l'arrivée de gaz et appelez immédiatement un pro."],
      ["Pannes les plus courantes", "Vase d'expansion, circulateur, sonde de température, vanne 3 voies, brûleur — pièces classiques sur 80% des dépannages."],
      ["Comment choisir son dépanneur", "Privilégiez un chauffagiste local certifié, qui pourra revenir en cas de récidive. Évitez les centrales d'appel anonymes — souvent plus chères."],
      ["L'astreinte sous contrat", "Si vous gérez un site critique (hôpital, copropriété, industrie), un contrat avec astreinte 24/7 est largement préférable au dépannage à la pièce."],
    ],
    relatedServices: ["maintenance-chaufferie"],
    publishedDate: "2026-01-28",
  },
];

// ---------- Realisations sample (used on home + zones) ----------
const REALIZATIONS = [
  ["Chaufferie", "Refonte chaufferie gaz", "Évry · 2 400 m² · 1.2 MW"],
  ["Aérotherme", "Installation 8 aérothermes", "Les Ulis · 5 800 m² · 480 kW"],
  ["Maintenance", "Contrat P2 chaufferie", "Orléans · 12 mois"],
  ["Plomberie", "Réseau eau industrielle", "Étampes · 1 200 m linéaire"],
];

// ---------- All cities (intervention zone) ----------
const ALL_CITIES = {
  "Essonne (91)": ["Étampes", "Dourdan", "Pussay", "Milly-la-Forêt", "Arpajon", "Brétigny", "Évry", "Les Ulis", "Massy", "Palaiseau"],
  "Loiret (45)": ["Orléans", "Pithiviers", "Montargis", "Gien", "Beaugency", "Olivet"],
  "Zones industrielles": ["ZI Brières-les-Scellés", "ZI Morangis", "ZI Les Ulis", "ZI Villebon", "ZI La Croix Blanche"],
};

module.exports = {
  SITE,
  CERTS,
  NAV,
  HUB_INDUSTRIEL_PATH,
  HUB_INDUSTRIEL_SLUG,
  SERVICES_INDUSTRIEL,
  SISTERS,
  LOCAL_INDUS,
  SERVICES_CHAUFFAGISTE,
  DEVIS_PAGES,
  BLOG_HUBS,
  BLOG_ARTICLES,
  REALIZATIONS,
  ALL_CITIES,
};
